#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("healthy_eating.Resource", IsApplication=true)]

namespace healthy_eating
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050001
			public const int allergic = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int lifestyles = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int cancel = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int default_button = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int default_TextView = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int food = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int healthy_eating = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int home = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ok = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int options = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int profile = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int search = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int stats = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int time = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int training = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int water = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int wei = 2130837521;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06001d
			public const int EatingList = 2131099677;
			
			// aapt resource value: 0x7f060023
			public const int button1 = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int button2 = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int button3 = 2131099685;
			
			// aapt resource value: 0x7f06003f
			public const int button_apply = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int button_cancel = 2131099712;
			
			// aapt resource value: 0x7f060036
			public const int button_choose_food = 2131099702;
			
			// aapt resource value: 0x7f060016
			public const int button_db_delete = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int button_db_destroy = 2131099672;
			
			// aapt resource value: 0x7f060015
			public const int button_db_save = 2131099669;
			
			// aapt resource value: 0x7f060013
			public const int button_db_select = 2131099667;
			
			// aapt resource value: 0x7f060037
			public const int button_delete = 2131099703;
			
			// aapt resource value: 0x7f06002b
			public const int button_food = 2131099691;
			
			// aapt resource value: 0x7f06002d
			public const int button_options = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int button_profile = 2131099694;
			
			// aapt resource value: 0x7f060011
			public const int editText_db_calories = 2131099665;
			
			// aapt resource value: 0x7f06000e
			public const int editText_db_carbs = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int editText_db_fats = 2131099659;
			
			// aapt resource value: 0x7f060005
			public const int editText_db_food = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int editText_db_proteins = 2131099656;
			
			// aapt resource value: 0x7f060038
			public const int edit_length = 2131099704;
			
			// aapt resource value: 0x7f06002f
			public const int edit_name = 2131099695;
			
			// aapt resource value: 0x7f06003c
			public const int edit_target_weight = 2131099708;
			
			// aapt resource value: 0x7f06003a
			public const int edit_weight = 2131099706;
			
			// aapt resource value: 0x7f060029
			public const int imageButton1 = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int imageButton2 = 2131099690;
			
			// aapt resource value: 0x7f06002c
			public const int imageButton4 = 2131099692;
			
			// aapt resource value: 0x7f060026
			public const int imageView1 = 2131099686;
			
			// aapt resource value: 0x7f060012
			public const int linearLayout1 = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int linearLayout2 = 2131099668;
			
			// aapt resource value: 0x7f060017
			public const int linearLayout3 = 2131099671;
			
			// aapt resource value: 0x7f06001e
			public const int linearLayout4 = 2131099678;
			
			// aapt resource value: 0x7f060022
			public const int linearLayout5 = 2131099682;
			
			// aapt resource value: 0x7f06003e
			public const int linearLayout6 = 2131099710;
			
			// aapt resource value: 0x7f060035
			public const int linearLayout7 = 2131099701;
			
			// aapt resource value: 0x7f060041
			public const int linear_buttons = 2131099713;
			
			// aapt resource value: 0x7f060030
			public const int radioGroup1 = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int radio_man = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int radio_woman = 2131099698;
			
			// aapt resource value: 0x7f060001
			public const int relativeLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060028
			public const int relativeLayout2 = 2131099688;
			
			// aapt resource value: 0x7f060027
			public const int relativeLayout4 = 2131099687;
			
			// aapt resource value: 0x7f060000
			public const int scrollView1 = 2131099648;
			
			// aapt resource value: 0x7f060039
			public const int seekbar_length = 2131099705;
			
			// aapt resource value: 0x7f06003d
			public const int seekbar_target_weight = 2131099709;
			
			// aapt resource value: 0x7f06003b
			public const int seekbar_weight = 2131099707;
			
			// aapt resource value: 0x7f060034
			public const int spinner_allergic = 2131099700;
			
			// aapt resource value: 0x7f060033
			public const int spinner_lifestyle = 2131099699;
			
			// aapt resource value: 0x7f060044
			public const int stat_calories = 2131099716;
			
			// aapt resource value: 0x7f060046
			public const int stat_pfc = 2131099718;
			
			// aapt resource value: 0x7f06004b
			public const int stat_training = 2131099723;
			
			// aapt resource value: 0x7f060048
			public const int stat_water = 2131099720;
			
			// aapt resource value: 0x7f060042
			public const int stat_weight = 2131099714;
			
			// aapt resource value: 0x7f060002
			public const int tableLayout1 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int tableRow1 = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int tableRow2 = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int tableRow3 = 2131099654;
			
			// aapt resource value: 0x7f06000f
			public const int tableRow4 = 2131099663;
			
			// aapt resource value: 0x7f06000c
			public const int tableRow5 = 2131099660;
			
			// aapt resource value: 0x7f060019
			public const int textView1 = 2131099673;
			
			// aapt resource value: 0x7f060004
			public const int textView16 = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int textView17 = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int textView18 = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int textView19 = 2131099661;
			
			// aapt resource value: 0x7f06001a
			public const int textView2 = 2131099674;
			
			// aapt resource value: 0x7f060010
			public const int textView20 = 2131099664;
			
			// aapt resource value: 0x7f06001b
			public const int textView3 = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int textView4 = 2131099676;
			
			// aapt resource value: 0x7f06001f
			public const int textView5 = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int textView6 = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int textView7 = 2131099681;
			
			// aapt resource value: 0x7f060049
			public const int textView9 = 2131099721;
			
			// aapt resource value: 0x7f060045
			public const int text_stat_calories = 2131099717;
			
			// aapt resource value: 0x7f060047
			public const int text_stat_pfc = 2131099719;
			
			// aapt resource value: 0x7f06004c
			public const int text_stat_training = 2131099724;
			
			// aapt resource value: 0x7f06004a
			public const int text_stat_water = 2131099722;
			
			// aapt resource value: 0x7f060043
			public const int text_stat_weight = 2131099715;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int db = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int default_ListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int foodlist = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int profile = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int temp = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
